Listar um Produot para um usuário #21
Murphyly/mate85_ecommerce pull request #22
Opened 2023-09-16 03:35 UTC by Shirkit

Implementado versão inicial da tela para listar um produto para um usuário.

Para testar, primeiro rode no instrumentations.js a importação dos dados de mockup padrão. Lembre-se que como foi alterado o schema prisma, precisa rodar um `npx prisma migrate reset` para resetar o DB. Se não quiser resetar o DB, tente `npx prisma migrate deploy` para tentar dar aplicar o novo schema.

2023-09-17 03:35 UTC, Shirkit commented
Pronto, agora podemos contar com `npm run dev-update-schema` para limpar a DB, aplicar as migrations e importar os dados de mockup para o banco.

2023-09-17 15:00 UTC, LucaMeireles-ufba approved these changes

2023-09-17 16:23 UTC, Murphyly commented
@LucaMeireles-ufba

2023-09-18 16:19 UTC, Murphyly requested changes
Precisa dar push sem as linhas comentadas para aprovarmos esse PR

2023-09-18 20:11 UTC, LucaMeireles-ufba commented
@Shirkit Consegue atualizar a branch removendo os comentários que impedem a execução?

2023-09-18 21:44 UTC, Murphyly approved these changes

2023-09-18 21:44 UTC, merged